name: Deploy Theme
on:
  push:	
    branches:	
      - sex
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: TryGhost/action-deploy-theme@v1.4.0
        with:
          api-url: ${{ secrets.SEX_ADMIN_API_URL }}
          api-key: ${{ secrets.SEX_ADMIN_API_KEY }}
